In [11]:
import pandas as pd
import numpy as np

In [12]:
df=pd.read_csv("perceptron_logistic_dataset.csv")

In [13]:
df.head()

   Feature_1  Feature_2  Target
0   0.199247  -0.116976       1
1  -0.248820  -0.731152       1
2  -0.354490  -0.708106       1
3  -1.590865  -2.011992       0
4  -0.200840   1.634932       1

In [14]:
X=df.iloc[:,:2]
X

    Feature_1  Feature_2
0    0.199247  -0.116976
1   -0.248820  -0.731152
2   -0.354490  -0.708106
3   -1.590865  -2.011992
4   -0.200840   1.634932
..        ...        ...
95  -2.123327   0.661988
96  -1.535998   0.071533
97  -1.460347   0.323236
98   0.836266  -0.345742
99  -0.265706   0.064999

[100 rows x 2 columns]

In [15]:
y=df.iloc[:,-1]
y

0     1
1     1
2     1
3     0
4     1
     ..
95    0
96    0
97    0
98    1
99    1
Name: Target, Length: 100, dtype: int64

In [29]:
def My_LogR(X,y):
    X=np.insert(X,0,1, axis=1)
    weight=np.ones(X.shape[1])
    learning_rate=0.5
    for i in range(2500):
        y_hat=Sigmoid(np.dot(X,weight))
#gradient haii    gradient = np.dot((y - y_hat), X) / X.shape[0]
        weight=weight + learning_rate*np.dot((y-y_hat),X)/X.shape[0]
    return weight[1:], weight[0]

In [30]:
def Sigmoid(z):
    return 1/(1+np.exp(-z))

In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [33]:
m, b = My_LogR(X_train, y_train)
m

array([9.77335928, 0.49777965])

In [34]:
b

np.float64(6.632787891057113)

In [35]:
def Predict(X, m, b):

    z = np.dot(X, m) + b

    y_hat = Sigmoid(z)

    return np.where(y_hat >= 0.5, 1, 0)

In [39]:
X_test

    Feature_1  Feature_2
83   1.376455  -1.089337
53   0.944153   0.173887
70  -2.396643  -0.842767
45   1.080598   0.916947
44  -0.805407  -0.113236
39   0.757272  -0.221006
22  -1.316906   0.102162
80  -0.161867   0.972475
10  -1.778289  -0.901146
0    0.199247  -0.116976
18  -0.182329   0.837271
30  -1.440756   0.270479
73  -1.457739  -0.165609
33   0.536885   0.170188
90   0.751635   0.194921
4   -0.200840   1.634932
76  -2.182546  -0.478898
77   0.963951   0.281283
12  -0.021942  -2.980924
31   1.349900  -0.758693

In [ ]:
y_test

In [36]:
y_pred = Predict(X_test, m, b)
y_pred

array([1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1])