In [3]:
import numpy as np
import pandas as pd

In [4]:
df=pd.read_csv('employee_attrition.csv')
df.head()

,Age,Department,MonthlyIncome,YearsAtCompany,DistanceFromHome,JobSatisfaction,OverTime,EducationLevel,WorkLifeBalance,NumCompaniesWorked,Attrition
0,59,Sales,57079.0,8,39.0,1.0,Yes,High School,1,4,Yes
1,49,HR,62266.0,23,17.0,4.0,Yes,High School,3,7,Yes
2,35,HR,39570.0,4,20.0,2.0,No,Bachelors,3,1,No
3,28,IT,69602.0,16,NaN,2.0,Yes,Bachelors,2,0,Yes
4,41,Marketing,52062.0,8,22.0,1.0,No,Masters,1,0,No

In [5]:
df.isnull().sum()

Age                    0
Department             0
MonthlyIncome         32
YearsAtCompany         0
DistanceFromHome      32
JobSatisfaction       32
OverTime               0
EducationLevel        32
WorkLifeBalance        0
NumCompaniesWorked     0
Attrition              0
dtype: int64

In [6]:
df.shape

(800, 11)

In [7]:
df = df.dropna()

In [8]:
df.isnull().sum()

Age                   0
Department            0
MonthlyIncome         0
YearsAtCompany        0
DistanceFromHome      0
JobSatisfaction       0
OverTime              0
EducationLevel        0
WorkLifeBalance       0
NumCompaniesWorked    0
Attrition             0
dtype: int64

In [9]:
df.shape

(677, 11)

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.columns.tolist()

['Age',
 'Department',
 'MonthlyIncome',
 'YearsAtCompany',
 'DistanceFromHome',
 'JobSatisfaction',
 'OverTime',
 'EducationLevel',
 'WorkLifeBalance',
 'NumCompaniesWorked',
 'Attrition']

In [12]:
df.dtypes

Age                     int64
Department             object
MonthlyIncome         float64
YearsAtCompany          int64
DistanceFromHome      float64
JobSatisfaction       float64
OverTime               object
EducationLevel         object
WorkLifeBalance         int64
NumCompaniesWorked      int64
Attrition              object
dtype: object

In [13]:
edu_order = {'High School':0, 'Bachelors':1, 'Masters':2, 'PhD':3}
df['EducationLevel'] = df['EducationLevel'].map(edu_order)

In [14]:
df = pd.get_dummies(df, columns=['Department'], dtype=int)

In [15]:
from sklearn.preprocessing import LabelEncoder
enco=LabelEncoder()
df['OverTime']= enco.fit_transform(df['OverTime'])
df['Attrition']=enco.fit_transform(df['Attrition'])
df.head()

,Age,MonthlyIncome,YearsAtCompany,DistanceFromHome,JobSatisfaction,OverTime,EducationLevel,WorkLifeBalance,NumCompaniesWorked,Attrition,Department_HR,Department_IT,Department_Marketing,Department_R&D,Department_Sales
0,59,57079.0,8,39.0,1.0,1,0,1,4,1,0,0,0,0,1
1,49,62266.0,23,17.0,4.0,1,0,3,7,1,1,0,0,0,0
2,35,39570.0,4,20.0,2.0,0,1,3,1,0,1,0,0,0,0
4,41,52062.0,8,22.0,1.0,0,2,1,0,0,0,0,1,0,0
5,59,67103.0,16,29.0,4.0,0,3,4,7,0,0,0,0,1,0

In [16]:
X=df.drop('Attrition',axis=1)
y=df['Attrition']
y

0      1
1      1
2      0
4      0
5      0
      ..
795    0
796    1
797    0
798    0
799    0
Name: Attrition, Length: 677, dtype: int64

In [17]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.2, random_state=2,stratify=y)

In [18]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train_sclr=scaler.fit_transform(X_train)
X_test_sclr=scaler.transform(X_test)

In [19]:
from sklearn.neighbors import KNeighborsClassifier

In [20]:
knn=KNeighborsClassifier(n_neighbors=35)
knn.fit(X_train_sclr,y_train)

KNeighborsClassifier(n_neighbors=35)

In [21]:
y_pred=knn.predict(X_test_sclr)

In [22]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [86]:
print(accuracy_score(y_test,y_pred))

0.6691176470588235

In [66]:
from sklearn.linear_model import LogisticRegression

In [89]:
logr=LogisticRegression()
logr.fit(X_train_sclr,y_train)

LogisticRegression(C=100)

In [90]:
yy=logr.predict(X_test_sclr)
print(accuracy_score(y_test,yy))

0.6838235294117647

# As model has NOISY data in target column
* Best accuracy for given dataset *