## Multiple Linear Regression
*No accuracy*

In [4]:
import numpy as np
import pandas as pd

In [5]:
df=pd.read_csv("house_price_pred.csv")
df.head()

   Area_in_Marla   Age  Price_in_PKR
0           21.9   6.6    15913000.0
1           47.8   8.3   133924000.0
2           37.9  17.2    64094000.0
3           31.9   7.0    13467000.0
4           12.0   4.2    85565000.0

In [11]:
X=df.iloc[:,:-1]
X

     Area_in_Marla   Age
0             21.9   6.6
1             47.8   8.3
2             37.9  17.2
3             31.9   7.0
4             12.0   4.2
..             ...   ...
245           46.8   7.7
246           24.3  12.1
247           48.5   2.5
248           48.4  19.5
249           43.4  19.7

[250 rows x 2 columns]

In [14]:
y=df.iloc[:,2]
y

0       15913000.0
1      133924000.0
2       64094000.0
3       13467000.0
4       85565000.0
          ...
245    122686000.0
246      6343000.0
247    168753000.0
248    183659000.0
249    129132000.0
Name: Price_in_PKR, Length: 250, dtype: float64

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.2, random_state=2)

In [17]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [23]:
y_pred=lr.predict(X_test)

In [24]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [25]:
score=r2_score(y_test,y_pred)
score

-0.022823961371353008

In [26]:
mae=mean_absolute_error(y_test,y_pred)
mae

38970840.87668336

In [27]:
mse=mean_squared_error(y_test,y_pred)
mse

1927113286007004.2

In [38]:
y_test

89      27542000.0
91      32734000.0
93       6030000.0
224     33251000.0
126     92557000.0
241    137187000.0
231     11379000.0
30      42614000.0
35      99482000.0
139    162792000.0
10     137979000.0
249    129132000.0
175     64173000.0
228    146301000.0
130     28168000.0
3       13467000.0
180     33995000.0
197    118492000.0
223     43124000.0
90      85196000.0
84      54106000.0
134    138725000.0
187     26443000.0
24       3266000.0
234     56197000.0
156     23953000.0
54      20911000.0
153     24175000.0
20      30990000.0
101     41131000.0
13      49440000.0
113     64152000.0
41      36732000.0
219    125073000.0
215     41770000.0
99      93653000.0
217     71141000.0
23      46252000.0
53     106919000.0
144     30800000.0
14      87898000.0
166     25631000.0
66      75819000.0
163      4830000.0
184     61806000.0
205    141614000.0
179     99753000.0
25      54908000.0
161     55356000.0
77     110094000.0
Name: Price_in_PKR, dtype: float64

In [28]:
from sklearn.preprocessing import PolynomialFeatures

In [32]:
poly=PolynomialFeatures(degree=2)

In [33]:
X_train_trans=poly.fit_transform(X_train)
X_test_trans=poly.transform(X_test)

In [34]:
X_train_trans[0]

array([1.00000e+00, 3.68000e+01, 1.91000e+01, 1.35424e+03, 7.02880e+02,
       3.64810e+02])

In [36]:
plr=LinearRegression()
plr.fit(X_train_trans,y_train)

LinearRegression()

In [39]:
y_pred=plr.predict(X_test_trans)

In [40]:
scr= r2_score(y_test,y_pred)
scr

0.9997952000556732

In [41]:
maee=mean_absolute_error(y_test,y_pred)
maee

491307.041935249

In [42]:
msee=mean_squared_error(y_test,y_pred)
msee

385865709634.32306